import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import React, { useMemo } from "react";
import { adoptionAdapter } from "./adoptionAdapter";
const Adoption = ({ rawdata, minified }) => {
    const result = useMemo(() => adoptionAdapter(rawdata), [rawdata]);
    console.log(result);
    if (!result) {
        return (_jsx("div", { className: "text-red-700 border-t border-gray-700 flex h-full items-center justify-center p-4 w-full text-center text-xl font-bold", children: _jsx("div", { children: "NO DATA..." }) }));
    }
    return (_jsxs("div", { className: "w-full flex flex-col gap-6", children: [!minified && (_jsx("div", { className: "text-2xl text-gray-300 font-bold mb-4 mt-8", children: "Adoption Rules Usage" })), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: `min-w-full ${!minified ? " bg-gray-800" : ""} overflow-hidden`, children: [!minified && (_jsx(_Fragment, { children: _jsx("thead", { className: "bg-gray-900", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider", children: "Rule" }), _jsx("th", { className: "text-center px-6 py-3 text-xs font-medium text-gray-300 uppercase tracking-wider", children: "is used" }), _jsx("th", { className: "text-center px-6 py-3 text-xs font-medium text-gray-300 uppercase tracking-wider", children: "adoption rate" }), _jsx("th", { className: "text-center px-6 py-3 text-xs font-medium text-gray-300 uppercase tracking-wider", children: "total occurences" }), _jsx("th", { className: "text-center px-6 py-3 text-xs font-medium text-gray-300 uppercase tracking-wider", children: "total debt occurences" })] }) }) })), _jsx("tbody", { className: "divide-y divide-gray-700", children: result.map((rule) => (_jsxs("tr", { className: "hover:bg-gray-700", children: [_jsxs("td", { className: "px-6 py-4 whitespace-nowrap text-sm text-gray-300", children: [_jsx("span", { className: "text-sm text-gray-300 font-bold uppercase", children: rule.name }), !minified && (_jsxs(_Fragment, { children: [_jsx("br", {}), _jsx("span", { className: "text-xs text-gray-400", children: rule.id })] }))] }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm text-gray-300 text-center", children: rule.isAdopted ? "✅" : "❌" }), _jsx("td", { className: "px-6 py-4 min-w-36 whitespace-nowrap text-sm text-gray-300", children: isNaN(rule.adoptionRate) ? (_jsx("div", { className: "w-full h-8 bg-red-950 relative", children: _jsx("span", { className: "absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-sm text-gray-100 font-semibold", children: "N/A" }) })) : (_jsxs("div", { className: "w-full h-8 bg-red-950 relative", children: [_jsx("div", { className: "h-full bg-green-700", style: {
                                                        width: `${Math.round(rule.adoptionRate * 100)}%`,
                                                    } }), _jsxs("span", { className: "absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-sm text-gray-100 font-semibold", children: [Math.round(rule.adoptionRate * 100), "%"] })] })) }), !minified && (_jsxs(_Fragment, { children: [_jsx("td", { className: "px-6 py-4 whitespace-nowrap text-lg text-gray-300 text-center", children: rule.totalScore }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-lg text-gray-300 text-center", children: rule.totalDebt >= 0 ? rule.totalDebt : "N/A" })] }))] }, rule.id))) })] }) })] }));
};
export default Adoption;
